import config from '../../config/index.js';
import { TYPE_ANALYZE, TYPE_SUM, TYPE_TRANSLATE } from '../../constants/command.js';
import COMMAND_ANALYZE_ANALYZE from './analyze-analyze.js';
import COMMAND_ANALYZE_LITERARILY from './analyze-literarily.js';
import COMMAND_ANALYZE_MATHEMATICALLY from './analyze-mathematically.js';
import COMMAND_ANALYZE_NUMEROLOGICALLY from './analyze-numerologically.js';
import COMMAND_ANALYZE_PHILOSOPHICALLY from './analyze-philosophically.js';
import COMMAND_ANALYZE_PSYCHOLOGICALLY from './analyze-psychologically.js';
import COMMAND_BOT_ACTIVATE from './bot-activate.js';
import COMMAND_BOT_CONTINUE from './bot-continue.js';
import COMMAND_BOT_DEACTIVATE from './bot-deactivate.js';
import COMMAND_BOT_DRAW_DEMO from './bot-draw-demo.js';
import COMMAND_BOT_DRAW from './bot-draw.js';
import COMMAND_BOT_FORGET from './bot-forget.js';
import COMMAND_BOT_GOOGLE_CALENDAR from './bot-google-calendar.js';
import COMMAND_BOT_GOOGLE_UNLINK from './bot-google-unlink.js';
import COMMAND_BOT_NOTE from './bot-note.js';
import COMMAND_BOT_NOTE_DELETE from './bot-note-delete.js';
import COMMAND_BOT_NOTE_LIST from './bot-note-list.js';
import COMMAND_BOT_RETRY from './bot-retry.js';
import COMMAND_BOT_SEARCH from './bot-search.js';
import COMMAND_BOT_TASK from './bot-task.js';
import COMMAND_BOT_TASK_DELETE from './bot-task-delete.js';
import COMMAND_BOT_TASK_DONE from './bot-task-done.js';
import COMMAND_BOT_TASK_LIST from './bot-task-list.js';
import COMMAND_BOT_TASK_REOPEN from './bot-task-reopen.js';
import COMMAND_BOT_QUIET_HOURS from './bot-quiet-hours.js';
import COMMAND_BOT_REMINDERS_PAUSE from './bot-reminders-pause.js';
import COMMAND_BOT_REMINDERS_RESUME from './bot-reminders-resume.js';
import COMMAND_BOT_SCHEDULE from './bot-schedule.js';
import COMMAND_BOT_SCHEDULE_CANCEL from './bot-schedule-cancel.js';
import COMMAND_BOT_SCHEDULE_COMPLETE from './bot-schedule-complete.js';
import COMMAND_BOT_SCHEDULE_CONFIRM from './bot-schedule-confirm.js';
import COMMAND_BOT_SCHEDULE_DELETE from './bot-schedule-delete.js';
import COMMAND_BOT_SCHEDULE_EDIT from './bot-schedule-edit.js';
import COMMAND_BOT_SCHEDULE_LIST from './bot-schedule-list.js';
import COMMAND_BOT_SCHEDULE_SYNC_DISMISS from './bot-schedule-sync-dismiss.js';
import COMMAND_BOT_SCHEDULE_SYNC_FAILED from './bot-schedule-sync-failed.js';
import COMMAND_BOT_SCHEDULE_SYNC_RETRY from './bot-schedule-sync-retry.js';
import COMMAND_BOT_TIMEZONE from './bot-timezone.js';
import COMMAND_BOT_SUMMON_DEMO from './bot-summon-demo.js';
import COMMAND_BOT_TALK_DEMO from './bot-talk-demo.js';
import COMMAND_BOT_TALK from './bot-talk.js';
import COMMAND_BOT_WEATHER from './bot-weather.js';
import COMMAND_BOT_WEATHER_COORDS from './bot-weather-coords.js';
import COMMAND_BOT_WEATHER_SUBSCRIBE from './bot-weather-subscribe.js';
import COMMAND_BOT_WEATHER_SUBSCRIPTIONS from './bot-weather-subscriptions.js';
import COMMAND_BOT_WEATHER_UNSUBSCRIBE from './bot-weather-unsubscribe.js';
import Command from './command.js';
import COMMAND_SUM_ADVISE from './sum-advise.js';
import COMMAND_SUM_APOLOGIZE from './sum-apologize.js';
import COMMAND_SUM_BLAME from './sum-blame.js';
import COMMAND_SUM_COMFORT from './sum-comfort.js';
import COMMAND_SUM_COMPLAIN from './sum-complain.js';
import COMMAND_SUM_ENCOURAGE from './sum-encourage.js';
import COMMAND_SUM_LAUGH from './sum-laugh.js';
import COMMAND_SUM_SUM from './sum-sum.js';
import COMMAND_SYS_COMMAND from './sys-command.js';
import COMMAND_SYS_DEPLOY from './sys-deploy.js';
import COMMAND_SYS_DOC from './sys-doc.js';
import COMMAND_SYS_REPORT from './sys-report.js';
import COMMAND_SYS_VERSION from './sys-version.js';
import COMMAND_TRANSLATE_TO_EN from './translate-to-en.js';
import COMMAND_TRANSLATE_TO_JA from './translate-to-ja.js';

export const ALL_COMMANDS = [
  COMMAND_ANALYZE_ANALYZE,
  COMMAND_ANALYZE_LITERARILY,
  COMMAND_ANALYZE_MATHEMATICALLY,
  COMMAND_ANALYZE_NUMEROLOGICALLY,
  COMMAND_ANALYZE_PHILOSOPHICALLY,
  COMMAND_ANALYZE_PSYCHOLOGICALLY,
  COMMAND_BOT_ACTIVATE,
  COMMAND_BOT_CONTINUE,
  COMMAND_BOT_DEACTIVATE,
  COMMAND_BOT_DRAW_DEMO,
  COMMAND_BOT_DRAW,
  COMMAND_BOT_FORGET,
  COMMAND_BOT_GOOGLE_CALENDAR,
  COMMAND_BOT_GOOGLE_UNLINK,
  COMMAND_BOT_NOTE,
  COMMAND_BOT_NOTE_DELETE,
  COMMAND_BOT_NOTE_LIST,
  COMMAND_BOT_RETRY,
  COMMAND_BOT_SEARCH,
  COMMAND_BOT_QUIET_HOURS,
  COMMAND_BOT_REMINDERS_PAUSE,
  COMMAND_BOT_REMINDERS_RESUME,
  COMMAND_BOT_SCHEDULE,
  COMMAND_BOT_SCHEDULE_CANCEL,
  COMMAND_BOT_SCHEDULE_COMPLETE,
  COMMAND_BOT_SCHEDULE_CONFIRM,
  COMMAND_BOT_SCHEDULE_DELETE,
  COMMAND_BOT_SCHEDULE_EDIT,
  COMMAND_BOT_SCHEDULE_LIST,
  COMMAND_BOT_SCHEDULE_SYNC_DISMISS,
  COMMAND_BOT_SCHEDULE_SYNC_FAILED,
  COMMAND_BOT_SCHEDULE_SYNC_RETRY,
  COMMAND_BOT_TIMEZONE,
  COMMAND_BOT_SUMMON_DEMO,
  COMMAND_BOT_TALK_DEMO,
  COMMAND_BOT_TALK,
  COMMAND_BOT_WEATHER,
  COMMAND_BOT_WEATHER_COORDS,
  COMMAND_BOT_WEATHER_SUBSCRIBE,
  COMMAND_BOT_WEATHER_SUBSCRIPTIONS,
  COMMAND_BOT_WEATHER_UNSUBSCRIBE,
  COMMAND_BOT_TASK,
  COMMAND_BOT_TASK_DELETE,
  COMMAND_BOT_TASK_DONE,
  COMMAND_BOT_TASK_LIST,
  COMMAND_BOT_TASK_REOPEN,
  COMMAND_SUM_ADVISE,
  COMMAND_SUM_APOLOGIZE,
  COMMAND_SUM_BLAME,
  COMMAND_SUM_COMFORT,
  COMMAND_SUM_COMPLAIN,
  COMMAND_SUM_ENCOURAGE,
  COMMAND_SUM_LAUGH,
  COMMAND_SUM_SUM,
  COMMAND_SYS_COMMAND,
  COMMAND_SYS_DEPLOY,
  COMMAND_SYS_DOC,
  COMMAND_SYS_REPORT,
  COMMAND_SYS_VERSION,
  COMMAND_TRANSLATE_TO_EN,
  COMMAND_TRANSLATE_TO_JA,
];

export const buildGeneralCommands = (features = config) => [
  ...(features.ENABLE_SCHEDULE ? [COMMAND_BOT_SCHEDULE, COMMAND_BOT_SCHEDULE_LIST] : []),
  ...(features.ENABLE_TASKS ? [COMMAND_BOT_TASK, COMMAND_BOT_TASK_LIST] : []),
  ...(features.ENABLE_WEATHER ? [COMMAND_BOT_WEATHER] : []),
  ...(features.ENABLE_WEATHER && features.ENABLE_WEATHER_PUSH
    ? [COMMAND_BOT_WEATHER_SUBSCRIBE] : []),
  ...(features.ENABLE_SEARCH ? [COMMAND_BOT_SEARCH] : []),
  ...(features.ENABLE_IMAGE_GENERATION ? [COMMAND_BOT_DRAW] : []),
  ...(features.ENABLE_GOOGLE_CALENDAR ? [COMMAND_BOT_GOOGLE_CALENDAR] : []),
  ...(features.ENABLE_REMINDERS
    ? [COMMAND_BOT_REMINDERS_PAUSE, COMMAND_BOT_REMINDERS_RESUME] : []),
  COMMAND_BOT_FORGET,
  COMMAND_SYS_COMMAND,
];

export const GENERAL_COMMANDS = buildGeneralCommands();

export const ENQUIRE_COMMANDS = ALL_COMMANDS.filter(({ type }) => (
  type === TYPE_SUM
  || type === TYPE_ANALYZE
  || type === TYPE_TRANSLATE
));

export {
  COMMAND_ANALYZE_ANALYZE,
  COMMAND_ANALYZE_LITERARILY,
  COMMAND_ANALYZE_MATHEMATICALLY,
  COMMAND_ANALYZE_NUMEROLOGICALLY,
  COMMAND_ANALYZE_PHILOSOPHICALLY,
  COMMAND_ANALYZE_PSYCHOLOGICALLY,
  COMMAND_BOT_ACTIVATE,
  COMMAND_BOT_CONTINUE,
  COMMAND_BOT_DEACTIVATE,
  COMMAND_BOT_DRAW_DEMO,
  COMMAND_BOT_DRAW,
  COMMAND_BOT_FORGET,
  COMMAND_BOT_GOOGLE_CALENDAR,
  COMMAND_BOT_GOOGLE_UNLINK,
  COMMAND_BOT_NOTE,
  COMMAND_BOT_NOTE_DELETE,
  COMMAND_BOT_NOTE_LIST,
  COMMAND_BOT_RETRY,
  COMMAND_BOT_SEARCH,
  COMMAND_BOT_QUIET_HOURS,
  COMMAND_BOT_REMINDERS_PAUSE,
  COMMAND_BOT_REMINDERS_RESUME,
  COMMAND_BOT_SCHEDULE,
  COMMAND_BOT_SCHEDULE_CANCEL,
  COMMAND_BOT_SCHEDULE_COMPLETE,
  COMMAND_BOT_SCHEDULE_CONFIRM,
  COMMAND_BOT_SCHEDULE_DELETE,
  COMMAND_BOT_SCHEDULE_EDIT,
  COMMAND_BOT_SCHEDULE_LIST,
  COMMAND_BOT_SCHEDULE_SYNC_DISMISS,
  COMMAND_BOT_SCHEDULE_SYNC_FAILED,
  COMMAND_BOT_SCHEDULE_SYNC_RETRY,
  COMMAND_BOT_TIMEZONE,
  COMMAND_BOT_SUMMON_DEMO,
  COMMAND_BOT_TALK_DEMO,
  COMMAND_BOT_TALK,
  COMMAND_BOT_WEATHER,
  COMMAND_BOT_WEATHER_COORDS,
  COMMAND_BOT_WEATHER_SUBSCRIBE,
  COMMAND_BOT_WEATHER_SUBSCRIPTIONS,
  COMMAND_BOT_WEATHER_UNSUBSCRIBE,
  COMMAND_BOT_TASK,
  COMMAND_BOT_TASK_DELETE,
  COMMAND_BOT_TASK_DONE,
  COMMAND_BOT_TASK_LIST,
  COMMAND_BOT_TASK_REOPEN,
  Command,
  COMMAND_SUM_ADVISE,
  COMMAND_SUM_APOLOGIZE,
  COMMAND_SUM_BLAME,
  COMMAND_SUM_COMFORT,
  COMMAND_SUM_COMPLAIN,
  COMMAND_SUM_ENCOURAGE,
  COMMAND_SUM_LAUGH,
  COMMAND_SUM_SUM,
  COMMAND_SYS_COMMAND,
  COMMAND_SYS_DEPLOY,
  COMMAND_SYS_DOC,
  COMMAND_SYS_REPORT,
  COMMAND_SYS_VERSION,
  COMMAND_TRANSLATE_TO_EN,
  COMMAND_TRANSLATE_TO_JA,
};
